[package]
name = "cve-2019-7317"
version = "0.1.0"
edition = "2024"

[dependencies]
libafl = { path = "../../../LibAFL/crates/libafl", features=["tui_monitor", "errors_backtrace"]}
libafl_bolts = { path = "../../../LibAFL/crates/libafl_bolts"}
libafl_targets = { path = "../../../LibAFL/crates/libafl_targets", features =["pointer_maps"]}
log = "0.4.28"

[build-dependencies]
bindgen = "0.72.1"
